# This is a config for E2B sandbox template.
# You can use template ID (tnaxtuf9uk4vtxmg4tvq) or template name (powerhouse) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("powerhouse") # Sync sandbox
# sandbox = await AsyncSandbox.create("powerhouse") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('powerhouse')

team_id = "e8651fb5-cbab-4253-9f50-03a102c8329e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "powerhouse"
template_id = "tnaxtuf9uk4vtxmg4tvq"
